// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yedjgjzfipccgwddvioq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllZGpnanpmaXBjY2d3ZGR2aW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODc3NDEsImV4cCI6MjA2Njg2Mzc0MX0.KiFHwOz3INqIUdOwx8abZ5BClN4zTDxNk77JlszbY9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});